export const GET_ROOMS = 'GET_ROOMS';
export const FILTER_ROOMS = 'FILTER_ROOMS';
export const CHANGE_THAT_STATE = 'CHANGE_THAT_STATE';
export const SET_LOADING = 'SET_LOADING';
export const GET_SINGLE_ROOM = 'GET_SINGLE_ROOM';